### ISSUE TITLE
缺个表吗？

### ISSUE THREAD

**Issue by Tdyh** [TeraDew/DjangoNovelSite#1]
![image](https://user-images.githubusercontent.com/26399336/76979326-bdd0fe00-6972-11ea-8330-2912e89046e6.png)

兄弟你能正常跑这个吗  刚开始学django的  为啥我跑你这个项目会提示我少一个表啊  我完全按照你的弄得虚拟环境  给我报这个错误
django.db.utils.OperationalError: no such table: users_user

**Comment by TeraDew** [comment]
你应该是没有创建用户，参考[这里](https://www.zmrenwu.com/courses/hellodjango-blog-tutorial/materials/62/)
这个博客给了我很多启发，向你推荐。

**Comment by Tdyh** [comment]
Ok  谢谢
